#!/usr/bin/env python3
"""Fetch BibTeX for papers that have a DOI.

Reads every `doi:` in _data/cv/papers.yml and makes sure each one has a BibTeX
entry in _data/citations.yml. Only DOIs missing from that file are requested,
from doi.org via content negotiation (Accept: application/x-bibtex), which
returns the metadata the publisher registered with Crossref or DataCite.
DOIs no longer used are dropped.

To fix an entry by hand, edit it in _data/citations.yml; the script never
overwrites an existing entry. Delete an entry to have it fetched again.
"""

import re
import sys
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "_data/cv/papers.yml"
CACHE = ROOT / "_data/citations.yml"
USER_AGENT = "research-site-citations (https://github.com/martins73/research-site)"
HEADER = (
    "# Generated by .github/scripts/fetch_citations.py from the doi fields in\n"
    "# _data/cv/papers.yml. Edit an entry only to correct it.\n"
)
MONTHS = {m[:3].lower(): m[:3].lower() for m in [
    "January", "February", "March", "April", "May", "June", "July",
    "August", "September", "October", "November", "December"]}


def fetch_bibtex(doi):
    req = urllib.request.Request(
        f"https://doi.org/{doi}",
        headers={"Accept": "application/x-bibtex", "User-Agent": USER_AGENT},
    )
    with urllib.request.urlopen(req, timeout=30) as res:
        text = res.read().decode("utf-8").strip()
    if not text.startswith("@"):
        raise ValueError("response is not BibTeX")
    return text


def split_fields(body):
    """Split 'a={x}, b={y, z}, c=Sept' into fields, respecting braces."""
    fields, depth, current = [], 0, ""
    for ch in body:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        if ch == "," and depth == 0:
            fields.append(current.strip())
            current = ""
        else:
            current += ch
    if current.strip():
        fields.append(current.strip())
    return fields


def tidy(bibtex):
    """One field per line, BibTeX-safe page ranges and month macros."""
    match = re.match(r"@(\w+)\{([^,]+),(.*)\}\s*$", bibtex, re.S)
    if not match:
        return bibtex
    kind, key, body = match.groups()
    lines = []
    for field in split_fields(body):
        name, _, value = field.partition("=")
        name, value = name.strip().lower(), value.strip()
        if name == "pages":
            value = value.replace("\u2013", "--").replace("\u2014", "--")
        if name == "month":
            value = MONTHS.get(value.strip("{}")[:3].lower(), value)
        if name == "url":
            continue  # Redundant with doi
        lines.append(f"  {name} = {value}")
    # Preprints are registered as articles with no journal, which BibTeX rejects
    if kind.lower() == "article" and not any(l.lstrip().startswith("journal ") for l in lines):
        kind = "misc"
        lines.append("  note = {Preprint}")
    return f"@{kind}{{{key},\n" + ",\n".join(lines) + "\n}"


def main():
    papers = yaml.safe_load(SOURCE.read_text(encoding="utf-8")).get("papers", [])
    dois = [str(p["doi"]).strip() for p in papers if p.get("doi")]
    cache = {}
    if CACHE.exists():
        cache = yaml.safe_load(CACHE.read_text(encoding="utf-8")) or {}

    for doi in dois:
        if doi in cache:
            continue
        try:
            cache[doi] = tidy(fetch_bibtex(doi))
            print(f"Fetched BibTeX for {doi}")
        except Exception as err:  # Keep going; the site falls back to generated BibTeX
            print(f"::warning::Could not fetch BibTeX for {doi}: {err}", file=sys.stderr)

    kept = {doi: cache[doi] for doi in dois if doi in cache}

    class Literal(str):
        pass

    yaml.add_representer(Literal, lambda d, v: d.represent_scalar("tag:yaml.org,2002:str", v, style="|"))
    body = yaml.dump({k: Literal(v) for k, v in kept.items()}, allow_unicode=True, sort_keys=True, width=1000) if kept else ""
    CACHE.write_text(HEADER + body, encoding="utf-8")


if __name__ == "__main__":
    main()
