#!/usr/bin/env python3
"""Geocode talk locations for the CV talks map.

Reads every `location:` in _data/cv/presentations.yml and makes sure each one
has coordinates in _data/talk_locations.yml. Only locations missing from that
file are looked up, through OpenStreetMap's Nominatim, at most one request per
second as its usage policy requires. Locations no longer used are dropped.

To fix a wrong match, edit its line in _data/talk_locations.yml by hand; the
script never overwrites an existing entry.
"""

import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "_data/cv/presentations.yml"
CACHE = ROOT / "_data/talk_locations.yml"
USER_AGENT = "research-site-talkmap (https://github.com/martins73/research-site)"
HEADER = (
    "# Generated by .github/scripts/geocode_talks.py from _data/cv/presentations.yml.\n"
    "# Used by the talks map on the CV page. Edit a line only to correct a wrong match.\n"
)
LOCATION_RE = re.compile(r'^\s*location:\s*["\']?(.+?)["\']?\s*$', re.M)
ENTRY_RE = re.compile(r'^"(.+)":\s*\{\s*lat:\s*(-?[\d.]+),\s*lon:\s*(-?[\d.]+)\s*\}', re.M)


def geocode(query):
    url = "https://nominatim.openstreetmap.org/search?" + urllib.parse.urlencode(
        {"q": query, "format": "json", "limit": 1}
    )
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as res:
        results = json.load(res)
    if not results:
        return None
    return round(float(results[0]["lat"]), 4), round(float(results[0]["lon"]), 4)


def main():
    locations = sorted(set(LOCATION_RE.findall(SOURCE.read_text(encoding="utf-8"))))
    cache = {}
    if CACHE.exists():
        for name, lat, lon in ENTRY_RE.findall(CACHE.read_text(encoding="utf-8")):
            cache[name] = (float(lat), float(lon))

    missing = [loc for loc in locations if loc not in cache]
    for i, loc in enumerate(missing):
        if i:
            time.sleep(1.1)
        coords = geocode(loc)
        if coords:
            cache[loc] = coords
            print(f"Geocoded {loc}: {coords[0]}, {coords[1]}")
        else:
            print(f"::warning::No match for '{loc}'; it will not appear on the map", file=sys.stderr)

    lines = [
        f'"{loc}": {{ lat: {cache[loc][0]}, lon: {cache[loc][1]} }}\n'
        for loc in locations if loc in cache
    ]
    CACHE.write_text(HEADER + "".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
