- role: "Admit Day Coordinator (Strategy, M&O, BDM, and Marketing)"
  organization: "UCLA Anderson School of Management"
  year: "2026"

- role: "Admit Day Coordinator (Strategy Department)"
  organization: "UCLA Anderson School of Management"
  year: "2022 - 2024"

- role: "Founding Board Member and Chair"
  organization: "Los Angeles Public Press"
  year: "2022 - Present"

- role: "Member | Board Member"
  organization: "California Donor Table"
  year: "2020 - 2023"

- role: "Member"
  organization: "Voices for Progress"
  year: "2019 - 2022"
